io-services:
  reader:
    class: org.jlab.jnp.grapes.io.HipoFrameReader
    name: HipoFrameReader
  writer:
    class: org.jlab.jnp.grapes.io.HipoFrameWriter
    name: HipoFrameWriter

services:
#  - class: org.jlab.jnp.grapes.services.JpsiTcsWagon
#    name: JPSITCS
  - class: org.jlab.jnp.grapes.services.DV1PipPimPWagon
    name: DV1PipPimP

configuration:
  services:
    JPSITCS:
      id: 1
    DVPipPimP:
      id: 2
      targetPDG: 2212
      beamEnergy: 10.604
    DV1PipPimP:
      id: 3
      targetPDG: 2212
      beamEnergy: 10.604

mime-types:
  - binary/data-hipo-frame
